# 
FROM node:14 as development
WORKDIR /home/node/app
ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV
ENV PATH /home/node/app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY . ./
CMD ["npm", "start"]
