version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - './frontend:/home/node/app'
      - '/home/node/app/node_modules'
    ports:
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true

# version: '3.7'
# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.prod
#       target: production
#     ports:
#       # Configure nginx to host on 8081
#       - 8081:80
